# Project information
site_name: Material Desingn 开发者文档
site_description: 'Material Components for Android'
site_author: '脉脉不得语'
site_url: 'https://materialdoc.cn'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/materialdoccn/materialdoc-web'

# Copyright
copyright: 'Copyright &copy; 2017 - 2024 Materialdoc CN'

# Documentation and theme
theme: 
  name: 'material'
  language: en
  logo: images/mddoc-logo.png
  favicon: images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: indigo=
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil 
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - content.action.edit
    - content.action.view
    - content.code.copy

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
    repository: materialdoccn/materialdoc-web
    branch: master
  - git-authors
  - glightbox
  - search
  - social
  - typeset
  - privacy

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/materialdoccn
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/inferjay
      name: Twitter
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/innferjay
      name: Weibo
  feature:
    tabs: true
  analytics:
    provider: google
    property: UA-71100105-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.


# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
    - Home:
      - 关于: index.md
      - 应用程序: application.md
      - 如何参与贡献: how-to-contribute.md
    - Components:
      - Auto-complete: components/autocomplete.md
      - Buttons: components/buttons.md
      - Buttons FAB: components/fab.md
      - Bottom navigation: components/bottom-navigation.md
      - Bottom sheets: components/bottom-sheets.md
      - Cards: components/cards.md
      - Dialogs: components/dialogs.md
      - Menus: components/menus.md
      - Pickers: components/pickers.md
      - Progress & activity: components/progress.md
      - Rating Bar: components/rating-bar.md
      - Selection controls: components/selection-controls.md
      - Snackbars & Toasts: components/snackbars-and-toasts.md
      - Tabs: components/tabs.md
      - Text fields: components/text-fields.md
      - Toolbars: components/toolbars.md
    - Patterns:
      - Data formats: patterns/data-formats.md
      - Launch screens: patterns/launch-screen.md
      - Navigation drawer: patterns/navigation-drawer.md
      - Notifications: patterns/notifications.md
      - Swipe to refresh: patterns/swipe-to-refresh.md
    # Pages which are not visible from menu
    - 'article-template.md'
